// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
)

const changePassword = `-- name: ChangePassword :exec
UPDATE users SET password=$1 WHERE _id=$2
`

type ChangePasswordParams struct {
	Password string `json:"password"`
	ID       int32  `json:"_id"`
}

func (q *Queries) ChangePassword(ctx context.Context, arg ChangePasswordParams) error {
	_, err := q.db.Exec(ctx, changePassword, arg.Password, arg.ID)
	return err
}

const checkIfusrExists = `-- name: CheckIfusrExists :one
SELECT _id FROM users WHERE email=$1
`

func (q *Queries) CheckIfusrExists(ctx context.Context, email string) (int32, error) {
	row := q.db.QueryRow(ctx, checkIfusrExists, email)
	var _id int32
	err := row.Scan(&_id)
	return _id, err
}

const loginUser = `-- name: LoginUser :one
SELECT _id, fullname,email,password FROM users WHERE email=$1
`

type LoginUserRow struct {
	ID       int32  `json:"_id"`
	Fullname string `json:"fullname"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

func (q *Queries) LoginUser(ctx context.Context, email string) (LoginUserRow, error) {
	row := q.db.QueryRow(ctx, loginUser, email)
	var i LoginUserRow
	err := row.Scan(
		&i.ID,
		&i.Fullname,
		&i.Email,
		&i.Password,
	)
	return i, err
}

const registerUser = `-- name: RegisterUser :one
INSERT INTO users (fullname,email,password)
VALUES ($1,$2,$3)
RETURNING _id
`

type RegisterUserParams struct {
	Fullname string `json:"fullname"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

func (q *Queries) RegisterUser(ctx context.Context, arg RegisterUserParams) (int32, error) {
	row := q.db.QueryRow(ctx, registerUser, arg.Fullname, arg.Email, arg.Password)
	var _id int32
	err := row.Scan(&_id)
	return _id, err
}
